apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pram-dask-scheduler
  name: pram-dask-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pram-dask-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pram-dask-scheduler
    spec:
      containers:
      - args:
        - conda
        - run
        - -n
        - pyenv
        - --no-capture-output
        - dask-scheduler
        image: dbsmith88/pram-dask:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        name: pram-dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
      dnsPolicy: ClusterFirst
      hostname: pram-dask-scheduler
      restartPolicy: Always
